# -*- coding: utf-8 -*-
"""chapter2_exercise_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13JmUoYeyFgfFUz1HzoX53dyw_SlEHHvT
"""

message ="I love painting"
print(message)

message ="painting of landscape"
print(message)