# -*- coding: utf-8 -*-
"""chapter2_exercise_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s6iP80BUBA_MNYNEiXWzJ1A2KPGMMooi
"""

print('Nelson Mandela once said, "It always seems impossible')
print('until its done."')